[package]
name = "limpet"
version = "0.3.0"
authors = [
  "Steve Hoffman <steveh@goofy.net>",
  "Journera Team <opensource@journera.com>"
]
edition = '2018'

[dependencies]
rustc-serialize = "0.3.24"
docopt = "0.6.83"
liquid = "0.20.1"
walkdir = "2.3.1"
